
- name: Copiar el archivo tpot.conf.dist.rhbicore
  copy:
    src: custom_files/tpot.conf.dist.rhbicore
    dest: /tpot/iso/installer/tpot.conf.dist.rhbicore
    owner: root
    group: root
    mode: '0644'

- name: Copiar tpot.conf.dist a tpot.conf
  command: cp tpot.conf.dist.rhbicore tpot.conf
  args:
    chdir: /tpot/iso/installer/
  register: cp_output

- name: Crear usuario adminrhbicore
  user:
    name: adminrhbicore
    password: "$6$mopVhUcTiaplxWe9$CS1PC3dTUVVvctuJybJjtAHEeiCVZObAWh/eP1SSJ56rDyXjub82LcL/BCGO.ISAN.S1JhR6Ru5xUznBVhrNs."
 
- name: Configurar sudo para adminrhbicore
  lineinfile:
    path: /etc/sudoers
    line: 'adminrhbicore    ALL=(ALL:ALL) ALL'
    validate: 'visudo -cf %s'

- name: Habilitar autenticación de contraseña en SSH
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "PasswordAuthentication yes"
    backup: yes

- name: Reiniciar SSH
  service:
    name: ssh
    state: restarted

- name: Crear usuario adminrhbicas
  user:
    name: adminrhbicas
    password: "$6$mopVhUcTiaplxWe9$CS1PC3dTUVVvctuJybJjtAHEeiCVZObAWh/eP1SSJ56rDyXjub82LcL/BCGO.ISAN.S1JhR6Ru5xUznBVhrNs."
 
- name: Configurar sudo para adminrhbicas
  lineinfile:
    path: /etc/sudoers
    line: 'adminrhbicas    ALL=(ALL:ALL) ALL'
    validate: 'visudo -cf %s'
   

- name: Comentar PasswordAuthentication en sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication no'
    line: '#PasswordAuthentication yes'

- name: Reiniciar SSH
  service:
    name: ssh
    state: restarted

- name: Ejecutar install.sh
  command: ./install.sh --type=auto --conf=tpot.conf
  args:
    chdir: /tpot/iso/installer/

- name: Pausa de 2 minutos
  pause:
    seconds: 120  # 120 segundos equivalen a 2 minutos


    


   




